spring:
  profiles:
    include: real-db # ec2에 존재함

  jpa:
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
