spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/monalisa
    #    url: jdbc:h2:mem:monalisa;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  pid:
    file: /home/ec2-user/app/step2/monalisa.pid

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

# 30분 1000 * 60 * 30
  access_token_expire_time : 1800000
# 24시간 1000 * 60 * 60 * 24
  refresh_token_expire_time : 864000000